/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package poo;

public class App {
public static void main(String[] args) {

    Tempo t1 = new Tempo();
    System.out.println(t1.toString());


    Tempo t2 = new Tempo(23);
    System.out.println(t2.toString());


    Tempo t3 = new Tempo(20,2,50);   
    System.out.println(t3.tempoSegundos());
    

    Tempo t4 = new Tempo(0,33,44);    
    System.out.println(t4.tempoSegundos());
    System.out.println(t4.diferencaSegundos(t3)); 

    



    
}

    
}
